import Head from 'next/head'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-blue-500 text-3xl font-bold'>
        Project X is a go
      </h1>
    </div>
  )
}
